"""Build ``examples/background_pack.parquet`` from real EcoSpold 1 files.

Source corpus: ``dev/BAFU ecospold/raw/ecoSpold files/`` -- ~12,000 EcoSpold 1
process files (``process_<uuid>.xml``), generated by openLCA. The root
element is ``<ecoSpold>`` with **no XML namespace**, so plain
``xml.etree.ElementTree`` tag names work directly:

    ecoSpold/dataset/metaInformation/processInformation/referenceFunction
    ecoSpold/dataset/flowData/exchange (repeated)

``referenceFunction`` carries the dataset's identity (``name``, ``unit``,
``amount`` -- always ``1`` in every file this script touches, i.e. every
``exchange`` below is already expressed per unit of the reference product).
Each ``exchange`` carries ``name``, ``category``, ``subCategory``, ``unit``
and ``meanValue``, plus exactly one of a nested ``<inputGroup>`` or
``<outputGroup>`` element.

**The elementary-vs-technosphere rule, found by inspecting the data rather
than assumed** (confirmed across the *entire* corpus -- every one of
11,947 files, no exceptions, via a full-corpus regex scan of every
``<inputGroup>``/``<outputGroup>`` value):

    outputGroup "0"   the dataset's reference product (exactly one per file)
    outputGroup "4"   an elementary flow emitted to the environment
                      (category one of "emissions to air/water/soil",
                      "non material emissions", "economic issues")
    inputGroup  "4"   an elementary flow drawn from the environment
                      (category "resources", always)
    inputGroup  "5"   a technosphere input -- materials, fuels, electricity,
                      services, infrastructure, waste treatment: this
                      process's own upstream, and exactly what a
                      "unit_process" background row does *not* resolve.

No other group codes occur anywhere in this corpus. Worked example
(``process_0004e814-c18d-42e2-a3f7-ce1fa51a3c2c.xml``, a nuclear-waste
repository dataset):

    <exchange name="Radioactive waste, ..." ...><outputGroup>0</outputGroup>   -> reference product
    <exchange name="Electricity, medium voltage, at grid" ...><inputGroup>5</inputGroup>   -> technosphere (dropped)
    <exchange name="Volume occupied, ..." category="resources" ...><inputGroup>4</inputGroup>   -> elementary (resource)
    <exchange name="Heat, waste" category="emissions to air" ...><outputGroup>4</outputGroup>   -> elementary (emission)

Every row this script writes carries ``basis="unit_process"``: these are
ecoinvent-style unit process datasets (a technology step with its own named
technosphere inputs), not Brightway ``lca.inventory`` results, so their
technosphere inputs are always dropped, never resolved. A dataset whose own
direct exchanges include none of the three flows below is not padded with an
empty row -- it is printed as skipped and left out. A demand for it still
gets no answer from this pack, which is what an honest cutoff is for.

**The flow mapping.** Only three elementary flows are mapped, because they
are the only ones this script's author is confident about (exact EcoSpold
name, unit and substance identity all checked against the corpus directly),
and a wrong IRI characterises as nothing, silently, which is worse than
leaving the flow out:

    "Carbon dioxide, fossil"  -> https://vocab.sentier.dev/flows/co2-fossil  (kg)
    "Methane, fossil"         -> https://vocab.sentier.dev/flows/ch4-fossil  (kg)
    "Dinitrogen monoxide"     -> https://vocab.sentier.dev/flows/n2o         (kg)

These three IRIs are the ones used everywhere in trailrunner
(``trailrunner/models/electricity.py``, ``trailrunner/assessment/dynamic.py``,
``trailrunner/models/natural_gas_pipeline_transport.py``). The pipeline model
once spelled two of them differently (``carbon-dioxide-fossil``,
``methane-fossil``); both have since been reconciled to the spelling below,
which is the one the characterization tables actually read.

Every other elementary flow this script finds (NOx, SO2, particulates,
NMVOC, noise, embodied water, ...) has no IRI mapping attempted here, and is
printed, deduplicated, when the script runs.

**The distribution/mixing/aggregation rule.** A dataset with none of the
three mapped flows is an easy call to leave out (see ``EXCLUDED`` above).
Harder: a dataset that *does* carry a mapped flow, but at a near-zero
amount, because its own direct exchanges are mostly a technosphere input of
the very commodity it produces -- e.g. "Electricity, high voltage, at grid"
(1 kWh out) whose only sizeable input is 1.028 kWh of "Electricity mix" (the
actual generation, one hop upstream and unresolved by this tier), leaving
only a trace of N2O as its own direct emission. Borrowing that row answers
an electricity demand with a plausible-looking near-zero for climate
impact -- worse than a cutoff, because a cutoff is visible.

``_distribution_step_reason`` catches this shape without naming
"electricity" anywhere: a unit process whose *largest* technosphere input is
(a) the same unit as its own reference product, (b) the same commodity --
judged by the leading word of both names before the first comma, e.g.
"Electricity" in both "Electricity mix" and "Electricity, high voltage, at
grid" -- and (c) within a small factor (0.5x-2x) of the reference amount, is
redistributing or blending that same commodity rather than making it.

**The rule is hand-audited against this pack, not fully structural.** Its
"largest" is a unit-blind ``max()`` over amounts in kg, MJ, kWh, m3 and tkm
alike, which is not a comparison that means anything on its own -- the
comparison only becomes meaningful at step (a), where an input of a
different unit is discarded. What follows is the audit, re-run against the
parsed files rather than remembered; every dominant input named here is the
one this script's own ``max()`` picks.

Only the two electricity rows (CH, RER) match all three conditions: their
dominant input is "Electricity mix", 1.028x and 1.035x their own 1 kWh, same
unit, same leading word. Every other kept dataset fails at least one:

- a different unit from the reference product: natural gas at consumer (m3
  of gas into an MJ reference), copper at refinery (4.53 MJ of heavy fuel
  oil), transport, freight, rail (kWh into tkm), transport, natural gas,
  pipeline (MJ into tkm), pig iron (1.51 MJ of blast furnace gas), steel,
  electric (0.751 MJ of natural gas), and aluminium, primary, liquid (14.9
  kWh of electricity);
- the same unit but a different leading word: clinker (1.25 kg of crushed
  limestone), hard coal at mine (1.68 kg of mine spoil disposal), steel,
  converter (0.9 kg of pig iron) -- real upstream materials, not the same
  commodity restated.

**Aluminium is the dataset this rule does not decide honestly.** It survives
only because the unit-blind ``max()`` lands on its 14.9 kWh of electricity,
which is then discarded for having the wrong unit. Look inside the reference
unit and it does contain a same-unit, same-leading-word, in-band input:
"Aluminium oxide, at plant", 1.92 kg per 1 kg of liquid aluminium. Do **not**
"harden" the rule to compare within the reference unit on the strength of
that: alumina into aluminium is the Hall-Heroult reduction, a genuine
producing step, and a rule that rejected it would throw away the one dataset
in this pack where electrolysis CO2 is actually recorded. The leading-word
heuristic simply cannot tell "aluminium oxide -> aluminium" (a reduction)
from "electricity mix -> electricity" (a redistribution); the pack's author
can, and did, one dataset at a time. Treat this function as a cheap guard
that caught the case it was written for, and audit any dataset added to
``DATASETS`` by hand.

Run:

    uv run python dev/build_background_pack.py

Writes ``examples/background_pack.parquet`` and prints what it kept and what
it skipped.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

CORPUS = Path(__file__).parent / "BAFU ecospold" / "raw" / "ecoSpold files"
OUT_PATH = Path(__file__).parent.parent / "examples" / "background_pack.parquet"

# EcoSpold exchange name -> (vocabulary IRI, expected unit). Only flows the
# author is confident about; see the module docstring.
ELEMENTARY_FLOW_MAP: dict[str, tuple[str, str]] = {
    "Carbon dioxide, fossil": ("https://vocab.sentier.dev/flows/co2-fossil", "kg"),
    "Methane, fossil": ("https://vocab.sentier.dev/flows/ch4-fossil", "kg"),
    "Dinitrogen monoxide": ("https://vocab.sentier.dev/flows/n2o", "kg"),
}

PRODUCTS = "https://vocab.sentier.dev/products/"

# Real BONSAI vocabulary concepts, verified live against
# https://vocab.sentier.dev (see dev/warm_pyst_cache.py and
# .superpowers/sdd/2026-09-22-phase-4-surfaces-and-showcase/step-0-report.md).
# These match trailrunner/models/electricity.py's ELECTRICITY and
# NATURAL_GAS constants -- the plain PRODUCTS + "electricity"/"natural-gas"
# IRIs below were invented, not vocabulary concepts. Every other
# ``PRODUCTS + "..."`` entry in DATASETS (hard-coal, copper,
# transport-freight-rail, transport-natural-gas-pipeline-long-distance,
# clinker, pig-iron, steel-low-alloyed, aluminium-primary) has not been
# checked against the vocabulary and keeps its invented IRI unchanged.
BONSAI = "https://vocab.sentier.dev/products/bonsai/2025.1/BONSAI2025.1/"
ELECTRICITY_IRI = BONSAI + "fi_17100"  # "electricity"
NATURAL_GAS_IRI = BONSAI + "fi_12020"  # "Natural gas, liquefied or in the gaseous state"

# Datasets actually found in the corpus by searching for their reference
# product name (not guessed by UUID), and confirmed -- by running this
# script's own parser over them -- to carry at least one of the three mapped
# elementary flows directly. ``expected_name`` is asserted against the
# file's own referenceFunction, so a corpus update that renames or replaces
# the file fails loudly instead of silently mismatching.
DATASETS: list[dict[str, Any]] = [
    {
        # Kept here, not moved to EXCLUDED, because it *was* searched for
        # under the brief's literal product name and does carry a mapped
        # elementary flow (N2O) directly -- but ``_distribution_step_reason``
        # rejects it at build time, structurally, before it reaches the pack:
        # its only sizeable direct exchange is ~1.03 kWh of "Electricity
        # mix", the same commodity one hop upstream. See the module
        # docstring's "distribution/mixing/aggregation rule".
        "file": "process_b29c2511-45c2-33b2-b08e-39580e0fe346.xml",
        "expected_name": "Electricity, high voltage, at grid",
        "expected_location": "CH",
        "product_iri": ELECTRICITY_IRI,
    },
    {
        # Same shape, same rejection -- see the CH entry above.
        "file": "process_5c40be39-7138-3b60-8d16-54298bca1926.xml",
        "expected_name": "Electricity, high voltage, at grid",
        "expected_location": "RER",
        "product_iri": ELECTRICITY_IRI,
    },
    {
        "file": "process_ede67f01-b29c-3537-8678-5c36efd1bad2.xml",
        "expected_name": "Natural gas, at consumer",
        "expected_location": "US",
        "product_iri": NATURAL_GAS_IRI,
    },
    {
        "file": "process_d265b9fd-31e7-35ba-80a8-4751e833d113.xml",
        "expected_name": "Hard coal, at mine",
        "expected_location": "WEU",
        "product_iri": PRODUCTS + "hard-coal",
    },
    {
        "file": "process_987dc6b3-6f8a-3736-8969-047831fe190f.xml",
        "expected_name": "Copper, primary, at refinery",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "copper",
    },
    {
        "file": "process_aacc6120-0e68-3835-8303-5ae37d62c030.xml",
        "expected_name": "Transport, freight, rail",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "transport-freight-rail",
    },
    {
        "file": "process_a4273d5b-5258-343d-9462-8369960dc122.xml",
        "expected_name": "Transport, natural gas, pipeline, long distance",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "transport-natural-gas-pipeline-long-distance",
    },
    {
        # Substitutes for "cement": the plain "Cement, unspecified, at
        # plant" dataset is checked below (see EXCLUDED) and turns out to be
        # a blending step with no direct elementary flows of its own.
        # Clinker -- the calcined component whose kiln is where cement's
        # process CO2 actually comes from -- is what the corpus has to offer
        # instead, under its own honest name and product IRI.
        "file": "process_137152eb-d111-382a-9eae-3e592047418d.xml",
        "expected_name": "Clinker, at plant",
        "expected_location": "CH",
        "product_iri": PRODUCTS + "clinker",
    },
    {
        "file": "process_9e2e5079-4890-30b5-b258-314be6f101e2.xml",
        "expected_name": "Pig iron, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "pig-iron",
    },
    {
        # Substitutes for "steel, low-alloyed": that exact dataset (see
        # EXCLUDED) turns out to be a further-processing step with no
        # direct elementary flows either. The converter (BOF) route does.
        "file": "process_c801854a-3e5e-3243-a4c0-4a3fcd7f54a3.xml",
        "expected_name": "Steel, converter, low-alloyed, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "steel-low-alloyed",
    },
    {
        "file": "process_e778ed60-5ec5-36e9-add5-745af0b58177.xml",
        "expected_name": "Steel, electric, low-alloyed, at plant",
        "expected_location": "CH",
        "product_iri": PRODUCTS + "steel-low-alloyed",
    },
    {
        # Substitutes for "aluminium, primary, at plant" (see EXCLUDED):
        # the liquid-at-plant dataset, one step upstream, is where the
        # electrolysis cell's direct CO2 is actually recorded.
        "file": "process_2d362b83-3248-39af-a3ca-fb3514ef12f1.xml",
        "expected_name": "Aluminium, primary, liquid, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "aluminium-primary",
    },
]

# Datasets that *were* searched for under the brief's literal product names
# and *are* in the corpus, but whose own direct exchanges carry none of the
# three mapped elementary flows -- every named substance they do carry
# (checked by hand against the parsed file, not guessed) is either
# unmapped or simply absent. Printed, not padded with an empty row: a
# borrowed dataset that emits nothing every reader can see is a cutoff by
# another name, and a real cutoff is more honest about it.
EXCLUDED: list[dict[str, str]] = [
    {
        "file": "process_b9430f24-d0b9-3422-a5ad-f874acbbef18.xml",
        "name": "Steel, low-alloyed, at plant (RER)",
        "reason": "every exchange is technosphere (inputGroup 5); this step "
        "is a further-processing/mixing stage, not the emitting one -- "
        "see 'Steel, converter/electric, low-alloyed' above instead",
    },
    {
        "file": "process_9dc7ef6a-1dcc-3968-b7ac-675141e0f5fa.xml",
        "name": "Concrete, normal, at plant (CH)",
        "reason": "its only elementary flow is 'Heat, waste' (unmapped); "
        "concrete's CO2 is embodied in its cement input, not this step",
    },
    {
        "file": "process_39f4c4a5-a5f8-3299-8841-9ab862d9e8fa.xml",
        "name": "Cement, unspecified, at plant (CH)",
        "reason": "every exchange is technosphere (inputGroup 5); this is a "
        "blending step -- see 'Clinker, at plant' above instead",
    },
    {
        "file": "process_5cac9857-21f7-305d-b705-c83a02a94e6e.xml",
        "name": "Aluminium, primary, at plant (RER)",
        "reason": "its elementary flows are SO2, NOx, particulates, HCl, "
        "water (all unmapped); none of the three mapped flows appear -- "
        "see 'Aluminium, primary, liquid, at plant' above instead",
    },
    {
        "file": "process_eb5552ed-63a8-374d-8fa4-296f644c37f8.xml",
        "name": "Transport, freight, lorry, 16t-32t gross weight, fleet average (CH, and every other weight class and location checked)",
        "reason": "every exchange is technosphere (inputGroup 5); this "
        "dataset family delegates combustion to a nested "
        "'Diesel/Petrol, burned in ...' technosphere process rather than "
        "carrying it directly",
    },
    {
        "file": "process_f9a96f35-a17a-3834-8e29-74b198153d89.xml",
        "name": "Heat, natural gas, at boiler condensing modulating 50kW (CH, and every other size and location checked)",
        "reason": "every exchange is technosphere (inputGroup 5); this "
        "dataset family delegates combustion to a nested "
        "'Natural gas, burned in boiler ...' technosphere process",
    },
]


def parse_dataset(path: Path) -> tuple[dict[str, str], list[tuple[str, str, str, str, float]]]:
    """Read one EcoSpold file: (reference-product identity, exchanges).

    Each exchange is ``(name, category, unit, group, meanValue)`` where
    ``group`` is ``"reference"`` (outputGroup 0), ``"elementary"``
    (outputGroup 4 or inputGroup 4) or ``"technosphere"`` (inputGroup 5) --
    the rule from the module docstring, applied here and nowhere else.
    """
    root = ET.parse(path).getroot()
    dataset = root.find("dataset")
    reference_function = dataset.find("metaInformation/processInformation/referenceFunction")
    geography = dataset.find("metaInformation/processInformation/geography")
    identity = {
        "name": reference_function.get("name"),
        "unit": reference_function.get("unit"),
        "amount": reference_function.get("amount"),
        "location": geography.get("location") if geography is not None else None,
    }

    exchanges: list[tuple[str, str, str, str, float]] = []
    for exchange in dataset.find("flowData").findall("exchange"):
        output_group = exchange.find("outputGroup")
        input_group = exchange.find("inputGroup")
        if output_group is not None and output_group.text == "0":
            group = "reference"
        elif (output_group is not None and output_group.text == "4") or (
            input_group is not None and input_group.text == "4"
        ):
            group = "elementary"
        elif input_group is not None and input_group.text == "5":
            group = "technosphere"
        else:
            raise ValueError(
                f"{path.name}: exchange {exchange.get('name')!r} has an "
                f"unrecognised inputGroup/outputGroup "
                f"({input_group.text if input_group is not None else None!r}/"
                f"{output_group.text if output_group is not None else None!r}); "
                "the rule this script relies on does not cover it"
            )
        exchanges.append(
            (
                exchange.get("name"),
                exchange.get("category"),
                exchange.get("unit"),
                group,
                float(exchange.get("meanValue")),
            )
        )
    return identity, exchanges


def _distribution_step_reason(
    identity: dict[str, str], exchanges: list[tuple[str, str, str, str, float]]
) -> str | None:
    """Structural check: is this dataset redistributing/blending its own
    reference product rather than producing it?

    A unit process whose *largest* technosphere input is the same commodity
    as its own reference product -- same unit, and within a small factor of
    the reference amount -- is a distribution, mixing or aggregation step,
    not a producing one: whatever it emits directly describes that step, not
    the product.

    "Same commodity" is judged the only way available from names alone: the
    leading word of both names, before the first comma, matches
    (``"Electricity"`` in both ``"Electricity mix"`` and ``"Electricity,
    high voltage, at grid"``). Deliberately narrow -- it does not fire on a
    same-unit input that is a genuinely different commodity (1.25 kg of
    crushed limestone into clinker, 0.9 kg of pig iron into converter
    steel).

    ``max()`` here is unit-blind, and stays that way: see the module
    docstring's "distribution/mixing/aggregation rule", which records the
    full audit against ``DATASETS``, and in particular why comparing within
    the reference unit would start rejecting alumina -> aluminium, a real
    producing step. This is a cheap guard that caught the case it was
    written for, not a structural test that can be trusted on a dataset
    nobody has audited.
    """
    technosphere = [
        (name, unit, amount) for name, _cat, unit, group, amount in exchanges if group == "technosphere"
    ]
    if not technosphere:
        return None
    dominant_name, dominant_unit, dominant_amount = max(technosphere, key=lambda t: t[2])

    ref_name = identity["name"]
    ref_unit = identity["unit"]
    ref_amount = float(identity["amount"])
    if dominant_unit != ref_unit:
        return None

    ref_word = ref_name.split(",", 1)[0].strip().split()[0].lower()
    dominant_word = dominant_name.split(",", 1)[0].strip().split()[0].lower()
    if ref_word != dominant_word:
        return None

    if ref_amount == 0:
        return None
    ratio = dominant_amount / ref_amount
    if not (0.5 <= ratio <= 2.0):
        return None

    return (
        f"largest technosphere input is {dominant_name!r} "
        f"({dominant_amount:g} {dominant_unit} per {ref_amount:g} {ref_unit} "
        f"of {ref_name!r}, ratio {ratio:.3g}) -- same commodity, same unit, "
        "within a small factor: a distribution/mixing/aggregation step, not "
        "a producing one"
    )


def build_rows() -> tuple[list[dict[str, Any]], set[str], list[dict[str, str]]]:
    rows: list[dict[str, Any]] = []
    skipped_flows: dict[str, int] = {}
    structural_skips: list[dict[str, str]] = []

    for entry in DATASETS:
        path = CORPUS / entry["file"]
        source = entry["file"].removeprefix("process_").removesuffix(".xml")
        identity, exchanges = parse_dataset(path)

        assert identity["name"] == entry["expected_name"], (
            f"{entry['file']}: expected referenceFunction name "
            f"{entry['expected_name']!r}, found {identity['name']!r}"
        )
        assert identity["location"] == entry["expected_location"], (
            f"{entry['file']}: expected location {entry['expected_location']!r}, "
            f"found {identity['location']!r}"
        )
        assert float(identity["amount"]) == 1.0, (
            f"{entry['file']}: referenceFunction amount is "
            f"{identity['amount']!r}, not 1 -- every meanValue below would "
            "need rescaling by it, and this script does not do that"
        )

        distribution_reason = _distribution_step_reason(identity, exchanges)
        if distribution_reason is not None:
            structural_skips.append(
                {
                    "name": f"{identity['name']} ({identity['location']})",
                    "reason": distribution_reason,
                }
            )
            print(f"skipped dataset: {identity['name']} ({identity['location']}) -- {distribution_reason}")
            continue

        found_any = False
        for name, _category, _unit, group, mean_value in exchanges:
            if group != "elementary":
                continue
            mapping = ELEMENTARY_FLOW_MAP.get(name)
            if mapping is None:
                skipped_flows[name] = skipped_flows.get(name, 0) + 1
                continue
            flow_iri, expected_unit = mapping
            rows.append(
                {
                    "product_iri": entry["product_iri"],
                    "product_unit": identity["unit"],
                    "location": identity["location"],
                    "dataset": identity["name"],
                    "source": source,
                    "basis": "unit_process",
                    "flow_iri": flow_iri,
                    "flow_unit": expected_unit,
                    "amount": mean_value,
                }
            )
            found_any = True

        assert found_any, (
            f"{entry['file']} ({identity['name']!r}) produced no rows -- it "
            "belongs in EXCLUDED, not DATASETS, if it has none of the mapped "
            "flows"
        )
        print(
            f"kept   {identity['name']} ({identity['location']}): "
            f"{sum(1 for r in rows if r['source'] == source)} row(s), source={source}"
        )

    return rows, skipped_flows, structural_skips


def print_excluded() -> None:
    for entry in EXCLUDED:
        print(f"skipped dataset: {entry['name']} -- {entry['reason']}")


def print_skipped_flows(skipped_flows: dict[str, int]) -> None:
    for name in sorted(skipped_flows):
        print(f"skipped flow (no confident IRI mapping): {name!r} (seen {skipped_flows[name]}x)")


def write_pack(rows: list[dict[str, Any]], path: Path) -> None:
    schema = pa.schema(
        [
            ("product_iri", pa.string()),
            ("product_unit", pa.string()),
            ("location", pa.string()),
            ("dataset", pa.string()),
            ("source", pa.string()),
            ("basis", pa.string()),
            ("flow_iri", pa.string()),
            ("flow_unit", pa.string()),
            ("amount", pa.float64()),
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows, schema=schema), path)


if __name__ == "__main__":
    rows, skipped_flows, structural_skips = build_rows()
    print()
    print_excluded()
    print()
    print_skipped_flows(skipped_flows)
    print()
    write_pack(rows, OUT_PATH)
    datasets = {(row["dataset"], row["location"]) for row in rows}
    print(f"wrote {OUT_PATH} ({len(rows)} rows, {len(datasets)} datasets)")
