"""Build ``examples/background_pack.parquet`` from real EcoSpold 1 files.

Source corpus: ``dev/BAFU ecospold/raw/ecoSpold files/`` -- ~12,000 EcoSpold 1
process files (``process_<uuid>.xml``), generated by openLCA. The root
element is ``<ecoSpold>`` with **no XML namespace**, so plain
``xml.etree.ElementTree`` tag names work directly:

    ecoSpold/dataset/metaInformation/processInformation/referenceFunction
    ecoSpold/dataset/flowData/exchange (repeated)

``referenceFunction`` carries the dataset's identity (``name``, ``unit``,
``amount`` -- always ``1`` in every file this script touches, i.e. every
``exchange`` below is already expressed per unit of the reference product).
Each ``exchange`` carries ``name``, ``category``, ``subCategory``, ``unit``
and ``meanValue``, plus exactly one of a nested ``<inputGroup>`` or
``<outputGroup>`` element.

**The elementary-vs-technosphere rule, found by inspecting the data rather
than assumed** (confirmed across the *entire* corpus -- every one of
11,947 files, no exceptions, via a full-corpus regex scan of every
``<inputGroup>``/``<outputGroup>`` value):

    outputGroup "0"   the dataset's reference product (exactly one per file)
    outputGroup "4"   an elementary flow emitted to the environment
                      (category one of "emissions to air/water/soil",
                      "non material emissions", "economic issues")
    inputGroup  "4"   an elementary flow drawn from the environment
                      (category "resources", always)
    inputGroup  "5"   a technosphere input -- materials, fuels, electricity,
                      services, infrastructure, waste treatment: this
                      process's own upstream, and exactly what a
                      "unit_process" background row does *not* resolve.

No other group codes occur anywhere in this corpus. Worked example
(``process_0004e814-c18d-42e2-a3f7-ce1fa51a3c2c.xml``, a nuclear-waste
repository dataset):

    <exchange name="Radioactive waste, ..." ...><outputGroup>0</outputGroup>   -> reference product
    <exchange name="Electricity, medium voltage, at grid" ...><inputGroup>5</inputGroup>   -> technosphere (dropped)
    <exchange name="Volume occupied, ..." category="resources" ...><inputGroup>4</inputGroup>   -> elementary (resource)
    <exchange name="Heat, waste" category="emissions to air" ...><outputGroup>4</outputGroup>   -> elementary (emission)

Every row this script writes carries ``basis="unit_process"``: these are
ecoinvent-style unit process datasets (a technology step with its own named
technosphere inputs), not Brightway ``lca.inventory`` results, so their
technosphere inputs are always dropped, never resolved. A dataset whose own
direct exchanges include none of the three flows below is not padded with an
empty row -- it is printed as skipped and left out. A demand for it still
gets no answer from this pack, which is what an honest cutoff is for.

**The flow mapping.** Only three elementary flows are mapped, because they
are the only ones this script's author is confident about (exact EcoSpold
name, unit and substance identity all checked against the corpus directly),
and a wrong IRI characterises as nothing, silently, which is worse than
leaving the flow out:

    "Carbon dioxide, fossil"  -> https://vocab.sentier.dev/flows/co2-fossil  (kg)
    "Methane, fossil"         -> https://vocab.sentier.dev/flows/ch4-fossil  (kg)
    "Dinitrogen monoxide"     -> https://vocab.sentier.dev/flows/n2o         (kg)

These three IRIs are the ones already used elsewhere in trailrunner
(``trailrunner/models/electricity.py``, ``trailrunner/assessment/dynamic.py``)
-- ``trailrunner/models/natural_gas_pipeline_transport.py`` uses a different
spelling (``carbon-dioxide-fossil``, ``methane-fossil``) for the same
substances; that inconsistency already exists in the codebase and is exactly
the kind of ambiguity this script refuses to paper over by picking a third
spelling. It follows the majority convention instead.

Every other elementary flow this script finds (NOx, SO2, particulates,
NMVOC, noise, embodied water, ...) has no IRI mapping attempted here, and is
printed, deduplicated, when the script runs.

Run:

    uv run python dev/build_background_pack.py

Writes ``examples/background_pack.parquet`` and prints what it kept and what
it skipped.
"""

import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

CORPUS = Path(__file__).parent / "BAFU ecospold" / "raw" / "ecoSpold files"
OUT_PATH = Path(__file__).parent.parent / "examples" / "background_pack.parquet"

# EcoSpold exchange name -> (vocabulary IRI, expected unit). Only flows the
# author is confident about; see the module docstring.
ELEMENTARY_FLOW_MAP: dict[str, tuple[str, str]] = {
    "Carbon dioxide, fossil": ("https://vocab.sentier.dev/flows/co2-fossil", "kg"),
    "Methane, fossil": ("https://vocab.sentier.dev/flows/ch4-fossil", "kg"),
    "Dinitrogen monoxide": ("https://vocab.sentier.dev/flows/n2o", "kg"),
}

PRODUCTS = "https://vocab.sentier.dev/products/"

# Datasets actually found in the corpus by searching for their reference
# product name (not guessed by UUID), and confirmed -- by running this
# script's own parser over them -- to carry at least one of the three mapped
# elementary flows directly. ``expected_name`` is asserted against the
# file's own referenceFunction, so a corpus update that renames or replaces
# the file fails loudly instead of silently mismatching.
DATASETS: list[dict[str, Any]] = [
    {
        "file": "process_b29c2511-45c2-33b2-b08e-39580e0fe346.xml",
        "expected_name": "Electricity, high voltage, at grid",
        "expected_location": "CH",
        "product_iri": PRODUCTS + "electricity",
    },
    {
        "file": "process_5c40be39-7138-3b60-8d16-54298bca1926.xml",
        "expected_name": "Electricity, high voltage, at grid",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "electricity",
    },
    {
        "file": "process_ede67f01-b29c-3537-8678-5c36efd1bad2.xml",
        "expected_name": "Natural gas, at consumer",
        "expected_location": "US",
        "product_iri": PRODUCTS + "natural-gas",
    },
    {
        "file": "process_d265b9fd-31e7-35ba-80a8-4751e833d113.xml",
        "expected_name": "Hard coal, at mine",
        "expected_location": "WEU",
        "product_iri": PRODUCTS + "hard-coal",
    },
    {
        "file": "process_987dc6b3-6f8a-3736-8969-047831fe190f.xml",
        "expected_name": "Copper, primary, at refinery",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "copper",
    },
    {
        "file": "process_aacc6120-0e68-3835-8303-5ae37d62c030.xml",
        "expected_name": "Transport, freight, rail",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "transport-freight-rail",
    },
    {
        "file": "process_a4273d5b-5258-343d-9462-8369960dc122.xml",
        "expected_name": "Transport, natural gas, pipeline, long distance",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "transport-natural-gas-pipeline-long-distance",
    },
    {
        # Substitutes for "cement": the plain "Cement, unspecified, at
        # plant" dataset is checked below (see EXCLUDED) and turns out to be
        # a blending step with no direct elementary flows of its own.
        # Clinker -- the calcined component whose kiln is where cement's
        # process CO2 actually comes from -- is what the corpus has to offer
        # instead, under its own honest name and product IRI.
        "file": "process_137152eb-d111-382a-9eae-3e592047418d.xml",
        "expected_name": "Clinker, at plant",
        "expected_location": "CH",
        "product_iri": PRODUCTS + "clinker",
    },
    {
        "file": "process_9e2e5079-4890-30b5-b258-314be6f101e2.xml",
        "expected_name": "Pig iron, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "pig-iron",
    },
    {
        # Substitutes for "steel, low-alloyed": that exact dataset (see
        # EXCLUDED) turns out to be a further-processing step with no
        # direct elementary flows either. The converter (BOF) route does.
        "file": "process_c801854a-3e5e-3243-a4c0-4a3fcd7f54a3.xml",
        "expected_name": "Steel, converter, low-alloyed, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "steel-low-alloyed",
    },
    {
        "file": "process_e778ed60-5ec5-36e9-add5-745af0b58177.xml",
        "expected_name": "Steel, electric, low-alloyed, at plant",
        "expected_location": "CH",
        "product_iri": PRODUCTS + "steel-low-alloyed",
    },
    {
        # Substitutes for "aluminium, primary, at plant" (see EXCLUDED):
        # the liquid-at-plant dataset, one step upstream, is where the
        # electrolysis cell's direct CO2 is actually recorded.
        "file": "process_2d362b83-3248-39af-a3ca-fb3514ef12f1.xml",
        "expected_name": "Aluminium, primary, liquid, at plant",
        "expected_location": "RER",
        "product_iri": PRODUCTS + "aluminium-primary",
    },
]

# Datasets that *were* searched for under the brief's literal product names
# and *are* in the corpus, but whose own direct exchanges carry none of the
# three mapped elementary flows -- every named substance they do carry
# (checked by hand against the parsed file, not guessed) is either
# unmapped or simply absent. Printed, not padded with an empty row: a
# borrowed dataset that emits nothing every reader can see is a cutoff by
# another name, and a real cutoff is more honest about it.
EXCLUDED: list[dict[str, str]] = [
    {
        "file": "process_b9430f24-d0b9-3422-a5ad-f874acbbef18.xml",
        "name": "Steel, low-alloyed, at plant (RER)",
        "reason": "every exchange is technosphere (inputGroup 5); this step "
        "is a further-processing/mixing stage, not the emitting one -- "
        "see 'Steel, converter/electric, low-alloyed' above instead",
    },
    {
        "file": "process_9dc7ef6a-1dcc-3968-b7ac-675141e0f5fa.xml",
        "name": "Concrete, normal, at plant (CH)",
        "reason": "its only elementary flow is 'Heat, waste' (unmapped); "
        "concrete's CO2 is embodied in its cement input, not this step",
    },
    {
        "file": "process_39f4c4a5-a5f8-3299-8841-9ab862d9e8fa.xml",
        "name": "Cement, unspecified, at plant (CH)",
        "reason": "every exchange is technosphere (inputGroup 5); this is a "
        "blending step -- see 'Clinker, at plant' above instead",
    },
    {
        "file": "process_5cac9857-21f7-305d-b705-c83a02a94e6e.xml",
        "name": "Aluminium, primary, at plant (RER)",
        "reason": "its elementary flows are SO2, NOx, particulates, HCl, "
        "water (all unmapped); none of the three mapped flows appear -- "
        "see 'Aluminium, primary, liquid, at plant' above instead",
    },
    {
        "file": "process_eb5552ed-63a8-374d-8fa4-296f644c37f8.xml",
        "name": "Transport, freight, lorry, 16t-32t gross weight, fleet average (CH, and every other weight class and location checked)",
        "reason": "every exchange is technosphere (inputGroup 5); this "
        "dataset family delegates combustion to a nested "
        "'Diesel/Petrol, burned in ...' technosphere process rather than "
        "carrying it directly",
    },
    {
        "file": "process_f9a96f35-a17a-3834-8e29-74b198153d89.xml",
        "name": "Heat, natural gas, at boiler condensing modulating 50kW (CH, and every other size and location checked)",
        "reason": "every exchange is technosphere (inputGroup 5); this "
        "dataset family delegates combustion to a nested "
        "'Natural gas, burned in boiler ...' technosphere process",
    },
]


def parse_dataset(path: Path) -> tuple[dict[str, str], list[tuple[str, str, str, float]]]:
    """Read one EcoSpold file: (reference-product identity, exchanges).

    Each exchange is ``(name, category, group, meanValue)`` where ``group``
    is ``"reference"`` (outputGroup 0), ``"elementary"`` (outputGroup 4 or
    inputGroup 4) or ``"technosphere"`` (inputGroup 5) -- the rule from the
    module docstring, applied here and nowhere else.
    """
    root = ET.parse(path).getroot()
    dataset = root.find("dataset")
    reference_function = dataset.find("metaInformation/processInformation/referenceFunction")
    geography = dataset.find("metaInformation/processInformation/geography")
    identity = {
        "name": reference_function.get("name"),
        "unit": reference_function.get("unit"),
        "amount": reference_function.get("amount"),
        "location": geography.get("location") if geography is not None else None,
    }

    exchanges: list[tuple[str, str, str, float]] = []
    for exchange in dataset.find("flowData").findall("exchange"):
        output_group = exchange.find("outputGroup")
        input_group = exchange.find("inputGroup")
        if output_group is not None and output_group.text == "0":
            group = "reference"
        elif (output_group is not None and output_group.text == "4") or (
            input_group is not None and input_group.text == "4"
        ):
            group = "elementary"
        elif input_group is not None and input_group.text == "5":
            group = "technosphere"
        else:
            raise ValueError(
                f"{path.name}: exchange {exchange.get('name')!r} has an "
                f"unrecognised inputGroup/outputGroup "
                f"({input_group.text if input_group is not None else None!r}/"
                f"{output_group.text if output_group is not None else None!r}); "
                "the rule this script relies on does not cover it"
            )
        exchanges.append(
            (exchange.get("name"), exchange.get("category"), group, float(exchange.get("meanValue")))
        )
    return identity, exchanges


def build_rows() -> tuple[list[dict[str, Any]], set[str]]:
    rows: list[dict[str, Any]] = []
    skipped_flows: dict[str, int] = {}

    for entry in DATASETS:
        path = CORPUS / entry["file"]
        source = entry["file"].removeprefix("process_").removesuffix(".xml")
        identity, exchanges = parse_dataset(path)

        assert identity["name"] == entry["expected_name"], (
            f"{entry['file']}: expected referenceFunction name "
            f"{entry['expected_name']!r}, found {identity['name']!r}"
        )
        assert identity["location"] == entry["expected_location"], (
            f"{entry['file']}: expected location {entry['expected_location']!r}, "
            f"found {identity['location']!r}"
        )
        assert float(identity["amount"]) == 1.0, (
            f"{entry['file']}: referenceFunction amount is "
            f"{identity['amount']!r}, not 1 -- every meanValue below would "
            "need rescaling by it, and this script does not do that"
        )

        found_any = False
        for name, _category, group, mean_value in exchanges:
            if group != "elementary":
                continue
            mapping = ELEMENTARY_FLOW_MAP.get(name)
            if mapping is None:
                skipped_flows[name] = skipped_flows.get(name, 0) + 1
                continue
            flow_iri, expected_unit = mapping
            rows.append(
                {
                    "product_iri": entry["product_iri"],
                    "product_unit": identity["unit"],
                    "location": identity["location"],
                    "dataset": identity["name"],
                    "source": source,
                    "basis": "unit_process",
                    "flow_iri": flow_iri,
                    "flow_unit": expected_unit,
                    "amount": mean_value,
                }
            )
            found_any = True

        assert found_any, (
            f"{entry['file']} ({identity['name']!r}) produced no rows -- it "
            "belongs in EXCLUDED, not DATASETS, if it has none of the mapped "
            "flows"
        )
        print(
            f"kept   {identity['name']} ({identity['location']}): "
            f"{sum(1 for r in rows if r['source'] == source)} row(s), source={source}"
        )

    return rows, skipped_flows


def print_excluded() -> None:
    for entry in EXCLUDED:
        print(f"skipped dataset: {entry['name']} -- {entry['reason']}")


def print_skipped_flows(skipped_flows: dict[str, int]) -> None:
    for name in sorted(skipped_flows):
        print(f"skipped flow (no confident IRI mapping): {name!r} (seen {skipped_flows[name]}x)")


def write_pack(rows: list[dict[str, Any]], path: Path) -> None:
    schema = pa.schema(
        [
            ("product_iri", pa.string()),
            ("product_unit", pa.string()),
            ("location", pa.string()),
            ("dataset", pa.string()),
            ("source", pa.string()),
            ("basis", pa.string()),
            ("flow_iri", pa.string()),
            ("flow_unit", pa.string()),
            ("amount", pa.float64()),
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows, schema=schema), path)


if __name__ == "__main__":
    rows, skipped_flows = build_rows()
    print()
    print_excluded()
    print()
    print_skipped_flows(skipped_flows)
    print()
    write_pack(rows, OUT_PATH)
    datasets = {(row["dataset"], row["location"]) for row in rows}
    print(f"wrote {OUT_PATH} ({len(rows)} rows, {len(datasets)} datasets)")
